#!/bin/zsh

now_playing() {
	np="$(playerctl metadata artist) - $(playerctl metadata title) $(playerctl metadata album)"
	if [[ -z $np ]]; then
		echo ""
	else
		echo $np
	fi
}

play_pause() {
  playerctl play-pause
}

next() {
  playerctl next
}

previous() {
  playerctl previous
}

$@
