[font]
# normal.family will automatically be applied to all styles
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 12

[keyboard]
bindings = [ 
{ key = "Up", mods = "Shift", action = "ScrollLineUp" },
{ key = "Down", mods = "Shift", action = "ScrollLineDown" }
]

